### ISSUE TITLE
Counter

### ISSUE THREAD

**Issue by mpagels** [mpagels/userstory-example#1]
## Value statement - a requirement, not a solution
As a **user** 
I need **possibiliy to count up and down** 
so that **I have a counter** 

## Description (Text, Scribble, Wireframe, Design)

![grafik](https://user-images.githubusercontent.com/54703643/196660847-4114a277-c37d-4161-ad95-dcf648b7c2b2.png)

## Acceptance criteria
- [ ] the app / component starts with a big zero
- [ ] when clicking the + button, the zero is increased
- [ ] when clicking the - minus button, the count is decreased
- [ ] if the count is already 0, the count can not decreased more

## Tasks
- [ ] read API documention
- [ ] write tests
- [ ] install styles-components

## Size
small / big
