### ISSUE TITLE
Signup screen

### ISSUE THREAD

**Issue by VladF146** [mpagels/userstory-example#4]
## Value statement
As a **user** I need **signup form** so that **I can use the application** 

## Description (Text, Scribble, Wireframe, Design)
A new user should be able to enter his/her data into a signup form.

## Acceptance criteria
- [ ] A logo should be present.
- [ ] A text should tell that this is the signup screen.
- [ ] An input for the email and password should be available.
- [ ] A button to send the data is present.
- [ ] A link to the login screen is available.

## Tasks
- [ ] Create a basic react layout with a form to collect the information.
- [ ] A link should navigate to the login screen.

## Size
small

**Comment by SergeBrakow** [comment]
A picture would be nice, but this way it is also understandable.
